name: Linter and Test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, develop]

jobs:
  linter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0

      - name: Read version from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Install
        env:
          VERSION: ${{ steps.package-node-version.outputs.version }}
        run: |
          echo "Version is ${{ env.VERSION }}"
          yarn install

      - name: Linter check
        run: |
          yarn lint
